"""Generate manifest.toml for every pack in this repo.

The migration tool the manifest spec (§8) assigns to this repo. Identity,
version, description, and the loader-verified surface come from the live
``Pack(...)`` object; pack dependencies come from the ``# requires=`` /
``integrates_with=`` docstring convention (which stops being the source
of truth the moment the manifest exists); capabilities and consumes come
from the same AST extraction CI validates against
(scripts/manifest_tools.py); the content hash comes from the runtime's
reference implementation.

Rerunnable and idempotent: edit a pack, rerun this script (or just
``python scripts/generate_manifests.py <pack>``) to refresh its hash.
CI fails on a stale hash by design: the pin only means something if it
is checked.

Usage:
    python scripts/generate_manifests.py            # all packs
    python scripts/generate_manifests.py chat mcp   # specific packs
"""

from __future__ import annotations

import importlib
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "scripts"))

from activegraph.packs.manifest import compute_content_hash  # noqa: E402

from manifest_tools import (  # noqa: E402
    extract_capability_registrations,
    extract_consumed_capabilities,
)

CREATED_AT = "2026-07-08T00:00:00Z"
AUTHOR = "Yohei Nakajima"
SOURCE_URL = "https://github.com/yoheinakajima/activegraph-packs"
RUNTIME_RANGE = ">=1.4,<2.0"
PYTHON_RANGE = ">=3.11"
DEP_RANGE = ">=0.1"  # honest floor for intra-repo pack deps


def _toml_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _toml_list(values: list[str]) -> str:
    return "[" + ", ".join(_toml_str(v) for v in values) + "]"


def _parse_dep_comments(init_text: str) -> tuple[list[str], list[str]]:
    """Read the '# requires=[...]' / 'integrates_with=[...]' convention."""
    def _grab(key: str) -> list[str]:
        match = re.search(rf'{key}\s*=\s*\[([^\]]*)\]', init_text)
        if not match:
            return []
        return re.findall(r'"([^"]+)"', match.group(1))

    return _grab("requires"), _grab("integrates_with")


def generate(pack_dir_name: str) -> str:
    pack_dir = REPO / "packs" / pack_dir_name
    module = importlib.import_module(f"packs.{pack_dir_name}")
    pack = module.pack

    requires, integrates = _parse_dep_comments((pack_dir / "__init__.py").read_text())
    capabilities = extract_capability_registrations(pack_dir)
    consumes = extract_consumed_capabilities(pack_dir)
    settings_schema = pack.settings_schema.__name__ if pack.settings_schema else ""

    lines = [
        "# Generated by scripts/generate_manifests.py; rerun after editing the",
        "# pack (CI verifies the content hash and the declared surface).",
        "",
        "[pack]",
        f"name = {_toml_str(pack.name)}",
        f"version = {_toml_str(pack.version)}",
        f"description = {_toml_str(' '.join(pack.description.split()))}",
        'license = "Apache-2.0"',
        "",
        "[pack.provenance]",
        f"authors = [{_toml_str(AUTHOR)}]",
        'authored_by = "human"',
        'generator = ""',
        f"source_url = {_toml_str(SOURCE_URL)}",
        f"created_at = {_toml_str(CREATED_AT)}",
        "",
        "[pack.integrity]",
        f"content_hash = {_toml_str(compute_content_hash(pack_dir))}",
        "",
        "[dependencies]",
        f"activegraph = {_toml_str(RUNTIME_RANGE)}",
        f"python = {_toml_str(PYTHON_RANGE)}",
        "python-deps = []",
    ]
    if requires:
        lines += ["", "[dependencies.packs]"]
        lines += [f"{name} = {_toml_str(DEP_RANGE)}" for name in requires]
    if integrates:
        lines += ["", "[dependencies.optional-packs]"]
        lines += [f"{name} = {_toml_str(DEP_RANGE)}" for name in integrates]
    lines += [
        "",
        "[surface]",
        f"object_types = {_toml_list([ot.name for ot in pack.object_types])}",
        f"relation_types = {_toml_list([rt.name for rt in pack.relation_types])}",
        f"behaviors = {_toml_list([b.name for b in pack.behaviors])}",
        f"tools = {_toml_list([t.name for t in pack.tools])}",
        f"settings_schema = {_toml_str(settings_schema)}",
    ]
    if consumes:
        lines += [f"consumes = {_toml_list(consumes)}"]
    for decl in capabilities:
        lines += [
            "",
            "[[surface.capabilities]]",
            f"provider = {_toml_str(decl['provider'])}",
            f"capability = {_toml_str(decl['capability'])}",
            f"risk_class = {_toml_str(decl['risk_class'])}",
            f"credential_ref = {_toml_str(decl['credential_ref'])}",
        ]
    lines += [
        "",
        "[fixtures]",
        'entrypoint = "fixtures/run_fixtures.py"',
        "deterministic = true",
        "",
    ]

    manifest_path = pack_dir / "manifest.toml"
    manifest_path.write_text("\n".join(lines))
    # The content hash excludes manifest.toml, so writing the manifest does
    # not invalidate the hash just written into it.
    return str(manifest_path.relative_to(REPO))


ALL_PACKS = [
    "core", "tool_gateway", "secrets", "memory_gateway", "identity_auth",
    "agent_profile", "entity", "communication", "chat", "email", "schedule",
    "telegram", "whatsapp", "mcp", "research", "codebase", "team_ops",
    "meeting", "bridges", "evolution",
]


if __name__ == "__main__":
    targets = sys.argv[1:] or ALL_PACKS
    for name in targets:
        print("wrote", generate(name))
